### ISSUE TITLE
Turing events recomendations

### ISSUE THREAD

**Issue by cassgvp** [alan-turing-institute/climate-informatics-2024#4]
# Phased event support

## Stage 1 – immediate deliverables (No Turing Events involvement). 
- [x] set the date: 22-24th/25th April 2023 (see however note about duration below)
- [ ] source venue: 
- [x] put a shell website in place: https://alan-turing-institute.github.io/climate-informatics-2024/
- [ ] start thinking about programme

## Stage 2 
- [ ] start late Jan
- [ ] registration
- [ ] programme planning.

> Support can start from January and allocate a little time the last two weeks in December for planning. I would imagine increasing work on our end January through to end of February. This would allow us to maintain our other commitments and at the same time support your event.  
 
To consider:
- [ ] Duration of event: would recommend a two-day event, three days could be considered too long nowadays.
- [ ] Start time: would recommend starting at 10.00 instead of 09.00, due to train issues nowadays.
- [ ] Outcomes vs delegate numbers: The recommendation is to get more of an understanding of the event outcomes rather than focusing too early in the process on the ideal number of delegates. Otherwise, there is a danger of having many delegates but low interaction.

Budget: 
- [ ] the budget may not be sufficient to cover the event format as it is suggested at the moment with three days, speaker expenses, venue hire, catering plus dinner and drinks.

Audience: 
- [ ] It would be beneficial to understand how we would access the suggested audience. Should there be something more, for example, a collaboration [annual meeting](https://eur01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.climateinformatics.org%2Fconferences%2F&data=05%7C01%7Ccgouldvanpraag%40turing.ac.uk%7C66504a9d2bbd44c10e6608dbc8b3a0f9%7C4395f4a7e4554f958a9f1fbaef6384f9%7C0%7C0%7C638324446042211421%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=DxwBwKZOYXXLS2k%2BIYm29SvjyNIt3X%2BbUT3Px%2BzH44I%3D&reserved=0) with Cambridge for example.

Your team: 
- [ ] It would be useful to know who is involved from your team and what each person is responsible for.

Turing mission: 
- [ ] If the goal of the event is to promote community building and knowledge exchange it would be good to hone in on this and see how this can be supported through the event and consider whether a three-day event with 100 to 150 delegates would achieve this.
